echo Build with g++ ...
g++     -std=c++20 main.cpp sc.cpp -o tempSpec

echo Build with clang++ ...
clang++ -std=c++20 main.cpp sc.cpp -o tempSpec_clang

echo Build with icpx ...
icpx    -std=c++20 main.cpp sc.cpp -o tempSpec_icx
